export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const CATEGORIA_ACTUAL = 'CATEGORIA_ACTUAL';
export const ELIMINAR_CATEGORIA = 'ELIMINAR_CATEGORIA';

//PErsonas
export const OBTENER_PERSONAS = 'OBTENER_PERSONAS';
export const AGREGAR_PERSONA = 'AGREGAR_PERSONA';
export const PERSONA_ACTUAL = "PERSONA_ACTUAL";