export const OBTENER_CATEGORIAS = 'OBTENER_CATEGORIAS';
export const AGREGAR_CATEGORIA = 'AGREGAR_CATEGORIA';
export const CATEGORIA_ACTUAL = 'CATEGORIA_ACTUAL';
export const ELIMINAR_CATEGORIA = 'ELIMINAR_CATEGORIA';